#pragma once
#include <glm/glm.hpp>

enum EmissionMode{
    EMISSION_PHYSICAL = 0, // Standard additive lighting
    EMISSION_ABSOLUTE = 1 // Multiplicative tinting/filtering
};

struct GPUMaterial{
    glm::vec3 albedo; // Base color
    float _pad0;

    glm::vec3 emission; // Emitted light color / tint color
    float emissionStrength; // Intensity multiplier

    float roughness; // 0 = mirror, 1 = matte
    float metallic; // 0 = dielectric, 1 = metal
    float transmission; // 0 = opaque, 1 = transparent
    float ior;

    glm::vec3 specularTint; // F0 color override
    float specular; // Specular strength multiplier

    float clearcoat; // Secondary glossy layer strength
    float clearcoatRoughness; // Coating roughness
    float subsurface; // Translucency amount
    int emissionMode; // EMISSION_PHYSICAL or EMISSION_ABSOLUTE

    glm::vec3 absorption; // Beer's Law absorption coefficients
    float sheen; // Fabric-like edge glow

    float subsurfaceRadius; // How far light can travel (in world units)
    float scatteringAnisotropy; // -1=backscatter, 0=isotropic, 1=forward
    float _pad1; // Alignment padding
    float _pad2;
};

class MaterialBuilder{
public:
    static GPUMaterial Default() {
        GPUMaterial m{};
        m.albedo = glm::vec3(0.5f);
        m.emission = glm::vec3(0.0f);
        m.emissionStrength = 0.0f;
        m.roughness = 0.5f;
        m.metallic = 0.0f;
        m.transmission = 0.0f;
        m.ior = 1.45f;
        m.specularTint = glm::vec3(1.0f);
        m.specular = 0.5f;
        m.clearcoat = 0.0f;
        m.clearcoatRoughness = 0.03f;
        m.subsurface = 0.0f;
        m.emissionMode = EMISSION_PHYSICAL;
        m.absorption = glm::vec3(0.0f); // ← Zero absorption by default
        m.sheen = 0.0f;
        m.subsurfaceRadius = 0.0f; // ← NEW
        m.scatteringAnisotropy = 0.0f; // ← NEW
        m._pad1 = 0.0f;
        m._pad2 = 0.0f;
        return m;
    }

    static GPUMaterial Lambertian(const glm::vec3& albedo) {
        auto m = Default();
        m.albedo = albedo;
        m.roughness = 1.0f;
        m.metallic = 0.0f;
        m.transmission = 0.0f;
        m.specular = 0.0f;
        return m;
    }

    static GPUMaterial Metal(const glm::vec3& albedo, float roughness = 0.0f) {
        auto m = Default();
        m.albedo = albedo;
        m.roughness = roughness;
        m.metallic = 1.0f;
        m.transmission = 0.0f;
        return m;
    }

    static GPUMaterial Dielectric(float ior = 1.5f, glm::vec3 absorption = glm::vec3(0.0f)) {
        auto m = Default();
        m.albedo = glm::vec3(1.0f);
        m.roughness = 0.0f;
        m.metallic = 0.0f;
        m.transmission = 1.0f;
        m.ior = ior;
        m.absorption = absorption; // ← Add this parameter
        return m;
    }

    static GPUMaterial Emissive(const glm::vec3& color, float strength = 1.0f) {
        auto m = Default();
        m.emission = color;
        m.emissionStrength = strength;
        m.emissionMode = EMISSION_PHYSICAL;
        m.albedo = glm::vec3(0.0f);
        m.roughness = 1.0f;
        return m;
    }

    static GPUMaterial Plastic(const glm::vec3& albedo, float roughness = 0.5f) {
        auto m = Default();
        m.albedo = albedo;
        m.roughness = roughness;
        m.metallic = 0.0f;
        m.ior = 1.45f;
        m.specular = 0.5f;
        return m;
    }

    static GPUMaterial Clearcoat(const glm::vec3& baseAlbedo,
                                 float baseRoughness = 0.6f,
                                 float clearcoatAmount = 1.0f,
                                 float clearcoatRoughness = 0.03f) {
        auto m = Default();
        m.albedo = baseAlbedo;
        m.roughness = baseRoughness; // Base layer roughness (can be rough)
        m.metallic = 0.0f; // Typically used on dielectrics
        m.clearcoat = clearcoatAmount; // Strength of clearcoat layer (0-1)
        m.clearcoatRoughness = clearcoatRoughness; // Coating smoothness (usually very low)
        m.transmission = 0.0f;
        return m;
    }

    // NEW: Color filter/tint effect
    static GPUMaterial ColorFilter(const glm::vec3& tintColor, float strength = 0.5f) {
        auto m = Default();
        m.emission = tintColor;
        m.emissionStrength = strength;
        m.emissionMode = EMISSION_ABSOLUTE;
        m.albedo = glm::vec3(0.0f);
        return m;
    }

    // NEW: Dark void
    static GPUMaterial DarkVoid(float strength = 0.9f) {
        auto m = Default();
        m.emission = glm::vec3(0.0f);
        m.emissionStrength = strength;
        m.emissionMode = EMISSION_ABSOLUTE;
        m.albedo = glm::vec3(0.0f);
        return m;
    }

    static GPUMaterial ColoredGlass(const glm::vec3& color, float ior = 1.5f, float density = 2.0f) {
        auto m = Default();

        // SURFACE:
        // Set Albedo to White (1.0).
        // This allows light to pass through the "surface" without losing energy immediately.
        // The color will be generated by the volume absorption below.
        m.albedo = glm::vec3(1.0f);

        m.roughness = 0.0f;
        m.metallic = 0.0f;
        m.transmission = 1.0f;
        m.ior = ior;

        // VOLUME:
        // We invert the color to get absorption coefficients.
        // If we want Red glass, we want to ABSORB Green and Blue.
        // High density = Darker/Thicker glass.
        glm::vec3 absorptionColor = glm::vec3(1.0f) - color;

        // Ensure we don't have negative absorption
        absorptionColor = glm::max(absorptionColor, glm::vec3(0.0f));

        m.absorption = absorptionColor * density;

        return m;
    }

    static GPUMaterial CarPaint(const glm::vec3& color,
                            float metalFlake = 0.0f) {
        auto m = Clearcoat(color, 0.4f, 1.0f, 0.01f);
        m.metallic = metalFlake;  // 0.0 = solid paint, 0.5 = metallic flake
        return m;
    }

    // Lacquered wood variant
    static GPUMaterial LacqueredWood(const glm::vec3& woodColor) {
        return Clearcoat(woodColor, 0.8f, 0.8f, 0.05f);
    }

    static GPUMaterial Velvet(const glm::vec3& color, float sheenAmount = 1.0f) {
        auto m = Default();
        m.albedo = color;
        m.roughness = 1.0f;      // Completely diffuse
        m.metallic = 0.0f;
        m.sheen = sheenAmount;   // Strong sheen for velvet
        return m;
    }

    // Satin fabric (mix of sheen and some specular)
    static GPUMaterial Satin(const glm::vec3& color) {
        auto m = Default();
        m.albedo = color;
        m.roughness = 0.6f;      // Slight specular
        m.metallic = 0.0f;
        m.sheen = 0.5f;          // Moderate sheen
        m.specular = 0.3f;       // Some specular gloss
        return m;
    }
};
